export const SapirTypes = {
  REGISTER: "@SAPIR/REGISTER",
  SUCCESS: "@SAPIR/SUCCESS",
  FAILURE: "@SAPIR/FAILURE",
  LOGIN: "@SAPIR/LOGIN",
  LOGOUT: "@SAPIR/LOGOUT",
  SEND_CONTACT: "@SAPIR/SEND_CONTACT",
  FORGOT: "@SAPIR/FORGOT",
}