export const SapirTypes = {
  REQUEST: "@SAPIR/REQUEST",
  SUCCESS: "@SAPIR/SUCCESS",
  FAILURE: "@SAPIR/FAILURE",
  LOGIN: "@SAPIR/LOGIN",
  LOGOUT: "@SAPIR/LOGOUT",
  SEND_CONTACT: "@SAPIR/SEND_CONTACT"
}